server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id : CUSTOMER-INFO-SERVICE
          uri: lb://CUSTOMER-INFO-SERVICE
          predicates:
            - Path= /api/v1/customer/**,/api/v1/client/**

        - id: CUSTOMER-INFO-INTEGRATION-SERVICE
          uri: lb://CUSTOMER-INFO-INTEGRATION-SERVICE
          predicates:
            - Path= /api/v1/integration/**